---
docker_arch_map:
  x86_64: amd64
  aarch64: arm64

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-buildx-plugin
  - docker-compose-plugin

docker_apt_keyring: /etc/apt/keyrings/docker.asc

# TCP socket defaults (used by tasks/tcp.yml)
docker_tcp_host: "0.0.0.0"
docker_tcp_port: 2375
docker_override_dir: /etc/systemd/system/docker.service.d
