---
all:
  vars:
    ansible_python_interpreter: auto_silent

  children:
    ProxmoxVirtualEnvironments:
      hosts:
        pve01:
          ansible_host: pve01.management.internal
        pve02:
          ansible_host: pve02.management.internal
        pve82:
          ansible_host: pve82.management.internal
        pve99:
          ansible_host: pve99.management.internal

    ProxmoxBackupServers:
      hosts:
        ProxmoxBackupServer:
          ansible_host: ProxmoxBackupServer.storage.internal

    apt_enabled:
        children:
          ProxmoxBackupServers:
          ProxmoxVirtualEnvironments: