---
influxdb_listen_address: "0.0.0.0:8086"
influxdb_data_dir: /var/lib/influxdb2
influxdb_config_dir: /etc/influxdb2

influxdb_org: home.rickzaki.com
influxdb_bucket: pve
influxdb_retention: 90d
influxdb_admin_user: admin
influxdb_admin_password: "{{ vault_influxdb_admin_password }}"
