---
# lxc_start_stopped.yml — Start stopped LXCs.
#
# Usage:
#   ansible-playbook playbooks/lxc_start_stopped.yml

- name: Check and start stopped LXCs
  hosts: "{{ lxc_target_hosts | default('all') }}"
  become: true
  gather_facts: false
  tasks:
    - name: Start stopped LXCs
      ansible.builtin.include_tasks: ../roles/lxc/tasks/start_stopped.yml
