---
- name: Shut down LXCs that were started for updates
  hosts: GitLab_runners
  become: true
  gather_facts: false
  tasks:
    - name: Shutdown LXC
      ansible.builtin.command: /usr/sbin/pct shutdown {{ proxmox_vmid }} --timeout 60
      delegate_to: "{{ pve_node }}"
      when: was_stopped | default(false)
